import UIKit

assert(LodySessionBannerKind.completed.rawValue == "completed")
assert(LodySessionBannerKind.attention.rawValue == "attention")
assert(LodySessionBannerKind(rawValue: "error") == nil)
assert(LodySessionBannerKind.completed.symbolName == "checkmark")
assert(LodySessionBannerKind.attention.symbolName == "exclamationmark")
assert(LodySessionBannerKind.completed.subtitleKey == "native.session.banner.completed")
assert(LodySessionBannerKind.attention.subtitleKey == "native.session.banner.attention")
assert(!LodySessionBannerKind.completed.sticky)
assert(LodySessionBannerKind.attention.sticky)
assert(LodySessionBannerKind.completed.feedback == .success)
assert(LodySessionBannerKind.attention.feedback == .warning)
let completed = LodySessionBannerView(title: "Done", kind: .completed)
let attention = LodySessionBannerView(title: "Need", kind: .attention)
precondition(completed.accessibilityIdentifier == "lody.session.banner")
precondition(attention.accessibilityIdentifier == "lody.session.banner")
print("PASS: session banner kind mapping")
