"""Home uses navigation search and the trailing tab opens creation without changing tabs."""
import sys
from driver import UI

ui = UI(sys.argv[1], sys.argv[2])
ui.element('new-session-tab')
if any(i.get('AXUniqueId') == 'xmark' and i.get('AXLabel') == 'Close' for i in ui.state()):
    ui.axe('tap', '--id', 'xmark', '--post-delay', '1')
ui.capture('home')
ui.axe('tap', '--id', 'new-session-tab', '--post-delay', '1')
ui.element('create-session-input')
ui.capture('create')

ui.axe('tap', '--label', '关闭新建会话', '--post-delay', '1')
ui.element('new-session-tab')
assert any(i.get('AXLabel') == '会话' and str(i.get('AXValue')) == '1' for i in ui.state())
ui.axe('tap', '--id', 'new-session-tab', '--post-delay', '1')
ui.element('create-session-input')
ui.axe('tap', '--label', '关闭新建会话', '--post-delay', '1')
ui.capture('returned')
ui.axe('tap', '--value', '搜索项目或会话', '--post-delay', '.5')
ui.axe('type', 'Search')
ui.element('ui-search')
assert not any(i.get('AXUniqueId') == 'ui-design' for i in ui.state())
ui.capture('search')
ui.axe('tap', '--label', 'Clear text')
ui.axe('type', 'Lody')
ui.element('project:ui:unassigned')
ui.capture('project-search')
ui.axe('tap', '--label', 'Clear text')
ui.axe('type', 'NoSuchSession')
ui.wait(lambda items: any(i.get('AXLabel') == '没有匹配的项目或会话' for i in items), 'Missing empty search state')
ui.capture('empty-search')
ui.axe('tap', '--label', 'Close', '--post-delay', '1')
ui.element('ui-design')
assert not any(i.get('AXUniqueId') == 'ui-search' for i in ui.state())
ui.capture('cancelled')
ui.axe('tap', '--label', '设置', '--post-delay', '1')
ui.axe('tap', '--id', 'new-session-tab', '--post-delay', '1')
ui.element('create-session-input')
ui.axe('tap', '--label', '关闭新建会话', '--post-delay', '1')
assert any(i.get('AXLabel') == '设置' and str(i.get('AXValue')) == '1' for i in ui.state())
ui.capture('settings-returned')
print('Trailing create opens repeatedly without changing tabs; navigation search finds archived sessions and cancels back to the inbox.')
